# Generated by Django 5.1.3 on 2024-11-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default name', max_length=100)),
                ('description', models.TextField(default='Default description')),
                ('selected', models.BooleanField(default=True)),
                ('website_link', models.CharField(default='Default website link', max_length=500)),
                ('position_link', models.CharField(default='Default position link', max_length=500)),
                ('max_table_size', models.IntegerField(default=0)),
            ],
        ),
    ]
